export type RackModuleType = 'Filter'
  | 'Envelope'
  | 'StepSequencer'
  | 'VoltageSequencer'
  | 'KeyboardInput'
  | 'Delay'
  | 'Output'
  | 'Gain'
  | 'Oscillator'
  | 'Recorder'
  | 'VoltageQuantizer'
  | 'Reverb';
