export type RackModuleType = 'Filter'
  | 'Envelope'
  | 'StepSequencer'
  | 'VoltageSequencer'
  | 'KeyboardInput'
  | 'MidiInput'
  | 'MidiCCInput'
  | 'Delay'
  | 'Output'
  | 'Gain'
  | 'Oscillator'
  | 'VoltageQuantizer'
  | 'Noise'
  | 'ClockDivider'
  | 'Reverb';
